AutoBid/Controllers/Buyer/BuyerController.cs
using AutoBid.Helper;
using AutoBid.Models.CarBuyer;
using Core.CarBuyer;
using Core.CarSeller;
using Service.AspUser;
using Service.CarBuyer;
using Service.CarSeller;
using Service.Seller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Auction;
using Service.Auction;
using AutoBid.Models.Auction;

namespace AutoBid.Controllers.Buyer
{
    [Authorize]
    public class BuyerController : Controller
    {
        private readonly ICarBuyerInfoService _buyerService;
        private readonly ICarSellerVehicleInfoService _carsellervehicleinfoService;
        private readonly ICarSellerVehicleImagesService _carsellervehicleimageService;
        private readonly IAspNetUserService _aspNetUserService;
        private readonly ICarSellerInfoService _carsellerinfoService;
        private readonly ISellerPersonalInfoService _sellerPersonalInfoService;
        private readonly IAuctionHouseService _auctionHouseService;
        private readonly IAuctionHouseSaleService _auctionHouseSaleService;
        private readonly IAuctionHouseAddEditVehicleService _auctionHouseAddEditVehicleService;
        private readonly IAuctionHouseCarSellingVehicleImagesService _auctionHouseCarSellingVehicleImagesService;
        private readonly ICarSellerVehicleFuelTypeService _carSellerVehicleFuelTypeService;



        public BuyerController(ICarBuyerInfoService buyerService,
            ICarSellerVehicleInfoService carsellervehicleinfoService,
            ICarSellerVehicleImagesService carsellervehicleimageService, IAspNetUserService aspNetUserService, ICarSellerInfoService carsellerinfoService, ISellerPersonalInfoService sellerPersonalInfoService, IAuctionHouseService auctionHouseService, IAuctionHouseSaleService auctionHouseSaleService, IAuctionHouseAddEditVehicleService auctionHouseAddEditVehicleService, ICarSellerVehicleFuelTypeService carSellerVehicleFuelTypeService, IAuctionHouseCarSellingVehicleImagesService auctionHouseCarSellingVehicleImagesService)
        {
            _buyerService = buyerService;
            _carsellervehicleinfoService = carsellervehicleinfoService;
            _carsellervehicleimageService = carsellervehicleimageService;
            _aspNetUserService = aspNetUserService;
            _carsellerinfoService = carsellerinfoService;
            _sellerPersonalInfoService = sellerPersonalInfoService;
            _auctionHouseService = auctionHouseService;
            _auctionHouseSaleService = auctionHouseSaleService;
            _auctionHouseAddEditVehicleService = auctionHouseAddEditVehicleService;
            _carSellerVehicleFuelTypeService = carSellerVehicleFuelTypeService;
            _auctionHouseCarSellingVehicleImagesService = auctionHouseCarSellingVehicleImagesService;
        }
        //
        // GET: /Buyer/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult VehiclesIBought()
        {
            string UserName = Request.RequestContext.HttpContext.User.Identity.Name;
            var UserDetails = _aspNetUserService.GetAspNetUserByUserName(UserName);
            if (UserDetails != null)
            {
                long id = UserDetails.AspNetUsersAdditionalInfoes.FirstOrDefault().ID;
                List<CarBuyerInfoModel> modelList = new List<CarBuyerInfoModel>();
                List<CarBuyerInfo> carbuyer = _buyerService.GetAllCarBuyerQueryable().Where<CarBuyerInfo>(u => u.IsBrought == true && u.UserID == id).ToList<CarBuyerInfo>();
                if (carbuyer != null)
                {
                    foreach (var item in carbuyer)
                    {
                        CarBuyerInfoModel model = new CarBuyerInfoModel();
                        model.Title = item.CarSellerVehicleInfo.Model.Modelname + " " + item.CarSellerVehicleInfo.Make.Makename + " " + item.CarSellerVehicleInfo.RegistrationNumber;
                        var image = _carsellervehicleimageService.GetCarSellerVehicleImageByVehicleID(item.CarSellerVehicleInfo.ID).FirstOrDefault().Filename;
                        if (image != null)
                            model.BuyerImage = "/Content/Assets/CarSellerImages/" + image;
                        else
                            model.BuyerImage = "/Content/images/noimage.jpg";
                        model.BuyDate = item.BuyDate.ToString("dd/MM/yyyy");
                        model.BuyingPrice = item.BuyingPrice.ToString();
                        modelList.Add(model);
                    }
                }
                return View(modelList);
            }
            else 
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult VehiclesIAmSelling()
        {
            string UserName = Request.RequestContext.HttpContext.User.Identity.Name;
            var UserDetails = _aspNetUserService.GetAspNetUserByUserName(UserName);
            if (UserDetails != null)
            {
                long id = UserDetails.AspNetUsersAdditionalInfoes.FirstOrDefault().ID;
                List<CarBuyerInfoModel> modelList = new List<CarBuyerInfoModel>();
                List<CarSellerInfo> CarSeller = _carsellerinfoService.GetAllCarSellerInfo().Where<CarSellerInfo>(s => s.UserID == id).ToList<CarSellerInfo>();
                if (CarSeller.Count > 0)
                {
                    foreach (var sell in CarSeller)
                    {
                        List<CarSellerVehicleInfo> carbuyer = _carsellervehicleinfoService.GetAllCarSellerVehicleInfo().Where<CarSellerVehicleInfo>(v => v.CarSellerInfoID == sell.ID).OrderByDescending(a => a.ID).ToList<CarSellerVehicleInfo>();
                        if (carbuyer != null)
                        {
                            foreach (var item in carbuyer)
                            {
                                CarBuyerInfoModel model = new CarBuyerInfoModel();
                                model.WayOfSellingID = Convert.ToInt32(sell.WayOfSelling);
                                model.WayOfSelling = sell.CarSellingOn.Way;
                                model.VehicleID = item.ID;
                                model.Title = item.Model.Modelname + " " + item.Make.Makename + " " + item.RegistrationNumber;
                                model.BuyerImages = _carsellervehicleimageService.GetCarSellerVehicleImageByVehicleID(item.ID);
                                var image = _carsellervehicleimageService.GetCarSellerVehicleImageByVehicleID(item.ID).FirstOrDefault();
                                if (image != null)
                                    model.BuyerImage = "/Content/Assets/CarSellerImages/" + image.Filename;
                                else
                                    model.BuyerImage = "/Content/images/noimage.jpg";
                                // model.BuyDate = item.a.ToString("dd/MM/yyyy");
                                model.BuyingPrice = item.Price.ToString();
                                model.IsSendToAuction = item.IsSendToAuction;
                                modelList.Add(model);
                            }
                        }
                    }
                    return View(modelList);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }



        }
        public ActionResult VehiclesShortlisted()
        {
            string UserName = Request.RequestContext.HttpContext.User.Identity.Name;
            var UserDetails = _aspNetUserService.GetAspNetUserByUserName(UserName);
            long id = UserDetails.AspNetUsersAdditionalInfoes.FirstOrDefault().ID;
            List<CarBuyerInfoModel> modelList = new List<CarBuyerInfoModel>();
            List<CarBuyerInfo> carbuyer = _buyerService.GetAllCarBuyerQueryable().Where<CarBuyerInfo>(u => u.IsShortlisted == true && u.UserID == id).ToList<CarBuyerInfo>();
            if (carbuyer != null)
            {
                foreach (var item in carbuyer)
                {
                    CarBuyerInfoModel model = new CarBuyerInfoModel();
                    model.Title = item.CarSellerVehicleInfo.Model.Modelname + " " + item.CarSellerVehicleInfo.Make.Makename + " " + item.CarSellerVehicleInfo.RegistrationNumber;
                    model.VehicleID = item.VehicleID;
                    model.EncodedVehicleID = CommonHelper.Base64Encode(item.VehicleID.ToString());
                    model.WayOfSelling = item.CarSellerVehicleInfo.CarSellerInfo.CarSellingOn.Way;
                    model.WayOfSellingID = Convert.ToInt32(item.CarSellerVehicleInfo.CarSellerInfo.WayOfSelling);

                    var image = _carsellervehicleimageService.GetCarSellerVehicleImageByVehicleID(item.CarSellerVehicleInfo.ID).FirstOrDefault().Filename;
                    if (image != null)
                        model.BuyerImage = "/Content/Assets/CarSellerImages/" + image;
                    else
                        model.BuyerImage = "/Content/images/noimage.jpg";
                    model.BuyDate = item.BuyDate.ToString("dd/MM/yyyy");
                    model.BuyingPrice = item.BuyingPrice.ToString();
                    modelList.Add(model);
                }
            }
            return View(modelList);
        }
        public ActionResult VehiclesOffersMade()
        {
            string UserName = Request.RequestContext.HttpContext.User.Identity.Name;
            var UserDetails = _aspNetUserService.GetAspNetUserByUserName(UserName);
            long id = UserDetails.AspNetUsersAdditionalInfoes.FirstOrDefault().ID;
            List<CarBuyerInfoModel> modelList = new List<CarBuyerInfoModel>();

AutoBid/Views/Buyer/BuyerAccount.cshtml
@model AutoBid.Models.CarBuyer.CarBuyerPersonalInfoModel
@{
    ViewBag.Title = "BuyerAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="section">
    <div class="container buyeraccountwrap">
        @Html.Partial("_BuyerLink")
        <div class="row">
            <div class="col-md-3">

                <ul class="nav bs-docs-sidenav accountmenu">
                    <li class="active"><a href="javascript:void(0);" class="btn-primary" onclick="AccountNavChange('personal',this)">Personal Information</a></li>
                    <li><a href="javascript:void(0);" class="btn-primary" onclick="AccountNavChange('address', this)">Addresses</a></li>
                    <li><a href="javascript:void(0);" class="btn-primary" onclick="AccountNavChange('payment', this)">Payment Information</a></li>
                    @*<li><a href="#" class="btn-primary" onclick="AccountNavChange('personal')">Customer Services</a></li>*@
                </ul>
            </div>
            <div class="col-md-9 accountcontent">
                <div class="row auction_house_content">
                    <div class="formbg2 mb20">
                        <div class="paymentDetails" id="accPersonal">
                            <div class="sellerfg_header">
                                Personal Information
                            </div>
                            <div class="inforow  headermagin">
                                <div class="row">
                                    <div class="col-md-3"><strong>Name:</strong></div>
                                    <div class="col-md-9">@Model.Title @Model.FirstName @Model.LastName</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"><strong>Email:</strong></div>
                                    <div class="col-md-9">@Model.Email</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"><strong>Contact No:</strong></div>
                                    <div class="col-md-9">@Model.ContactNo</div>
                                </div>
                            </div>
                        </div>
                        <div class="paymentDetails" id="accAddress" style="display:none;">
                            <div class="sellerfg_header">
                               Address
                            </div>
                            <div class="inforow  headermagin">
                                <div class="row">
                                    <div class="col-md-3"><strong>Address:</strong></div>
                                    <div class="col-md-9">@Model.Address</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"><strong>Postal Code:</strong></div>
                                    <div class="col-md-9">@Model.PostalCode</div>
                                </div>
                                @*<div class="row">
                                    <div class="col-md-3"><strong>Contact No:</strong></div>
                                    <div class="col-md-9">@Model.ContactNo</div>
                                </div>*@
                            </div>
                        </div>
                        <div class="paymentDetails" id="accPayment" style="display:none;">
                            <div class="sellerfg_header">
                                Payment Information
                            </div>
                            <div class="inforow  headermagin">
                                <div class="row">
                                    <div class="col-md-3"><strong>No Information Available</strong></div>
                                    <div class="col-md-9"></div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"><strong></strong></div>
                                    <div class="col-md-9"></div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"><strong></strong></div>
                                    <div class="col-md-9"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var AccountNavChange = function (type,that) {
        $(".accountmenu>li").removeClass("active");
        $(that).parent().addClass("active")
        if (type.toLowerCase() == "personal")
        {
            $("#accPersonal").show();
            $("#accAddress").hide();
            $("#accPayment").hide();
        }
        else if (type.toLowerCase() == "address") {
            $("#accAddress").show();
            $("#accPersonal").hide();
            $("#accPayment").hide();
        }
        else if (type.toLowerCase() == "payment") {
            $("#accPayment").show();
            $("#accAddress").hide();
            $("#accPersonal").hide();
        }
    }
</script>

AutoBid/Views/Buyer/VehiclesIBought.cshtml
@{
    ViewBag.Title = "Vehicles I Bought";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section">
    <div class="container">
        @Html.Partial("_BuyerLink")
        <div class="row">
            <div class="col-md-9">
                <div class="row auction_house_content">

                    <h1>Vehicles Bought</h1>
                    <div class="col-md-12">
                        <table width="100%" id="VehiclesIBought" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th> </th>
                                    <th> </th>
                                    <th>Title</th>
                                    <th>Date bought</th>
                                    <th>Price</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int count = 1;
                                    foreach (var item in Model)
                                    {

                                        <tr>
                                            <td>@Html.Label(count.ToString())</td>
                                            <td width="25%"><img src="@item.BuyerImage" alt="@item.BuyerImage" class="thumbnail" width="100%" />   </td>
                                            <td width="25%">@item.Title</td>
                                            <td width="25%">@item.BuyDate</td>
                                            <td width="25%">@item.BuyingPrice £</td>
                                            <td width="25%"></td>
                                        </tr>
                                        count = count + 1;
                                    }
                                }
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="adbanner">
                    <span>Ad Banner</span>
                </div>
            </div>
        </div>

        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>


<script>
    $(document).ready(function () {
        $('#VehiclesIBought').dataTable();
    });
</script>

AutoBid/Views/Buyer/VehiclesOffersMade.cshtml
@model List<AutoBid.Models.CarBuyer.CarBuyerInfoModel>
@{
    ViewBag.Title = "Offers Made";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section">
    <div class="container">
        @Html.Partial("_BuyerLink")
        <div class="row">
            <div class="col-md-9">
                <div class="row auction_house_content">

                    <h1>Offers made</h1>
                    <div class="col-md-12">
                        <table width="100%" id="OffersMade" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th> </th>
                                    <th> </th>
                                    <th> </th>
                                    <th>Title</th>
                                    <th> </th>
                                    <th>Offer Made</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int count = 1;
                                    foreach (var item in Model)
                                    {

                                        <tr>
                                            <td width="1%" >@Html.Label(count.ToString())</td>
                                            <td width="10%">@item.BuyDate</td>
                                            <td width="24%"><img src="@item.BuyerImage" alt="@item.BuyerImage" class="thumbnail" width="100%" />   </td>
                                            <td width="20%">@item.Title</td>
                                            <td width="15%">@item.WayOfSelling</td>
                                            @*<td width="25%">@item.BuyDate</td>*@
                                            <td width="10%">@item.BuyingPrice £</td>
                                            <td width="20%" valign="middle">
                                                <div class="increaseOffer"><a class="btn btn-danger" href="javascript:void(0)">Increase Offer</a></div>
                                                <div class="makeCounterOffer"><a class="btn btn-success" href="javascript:void(0)">Make Counter Offer</a></div>
                                            </td>
                                        </tr>
                                        count = count + 1;
                                    }
                                }
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="adbanner">
                    <span>Ad Banner</span>
                </div>
            </div>
        </div>

        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>


<script>
    $(document).ready(function () {
        $('#OffersMade').dataTable();
    });
</script>

AutoBid/Views/Buyer/VehiclesShortlisted.cshtml
@model List<AutoBid.Models.CarBuyer.CarBuyerInfoModel>
@{
    ViewBag.Title = "Shortlisted Vehicles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section">
    <div class="container">
        @Html.Partial("_BuyerLink")
        <div class="row">
            <div class="col-md-9">
                <div class="row auction_house_content">

                    <h1>Vehicles Shortlisted</h1>
                    <div class="col-md-12">
                        <table width="100%" id="VehiclesShortlisted" border="0" cellspacing="0" cellpadding="0" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th> </th>
                                    <th> </th>
                                    <th> </th>
                                    <th>Sale Date</th>
                                    <th>Price</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int count = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td width="1%">@Html.Label(count.ToString())</td>
                                            <td width="24%"><img src="@item.BuyerImage" alt="@item.BuyerImage" class="thumbnail" width="100%" />   </td>
                                            <td width="20%">@item.Title</td>
                                            @if(@item.WayOfSellingID==1)
                                            {
                                                <td width="15%">@item.WayOfSelling</td>
                                            }
                                            else
                                            { 
                                            <td width="15%">@item.BuyDate</td>
                                            }
                                            
                                            <td width="15%">£ @item.BuyingPrice </td>
                                            <td width="25%">
                                               @if(@item.WayOfSellingID==2)
                                                {
                                                <div class="increaseOffer">
                                                    <a class="btn btn-info" href="javascript:void(0)"><span class="fa fa-mail-reply"></span>Contact Auction</a>
                                                </div>

                                                <div class="makeCounterOffer">
                                                    <a class="btn btn-info" href="javascript:void(0)"><span class="fa fa-gavel"></span>Commission Bid</a>
                                                </div>
                                                <div class="makeCounterOffer">
                                                    <a class="btn btn-info" href="javascript:void(0)">
                                                        <span class="fa fa-eye"></span>
                                                        View other vehicles in sales
                                                    </a>
                                                </div>
                                                <div class="makeCounterOffer">
                                                    <a class="btn btn-info" href="javascript:void(0)">
                                                        <span class="fa fa-user"></span>
                                                        Send to a friend
                                                    </a>
                                                </div>
                                                <div class="makeCounterOffer">
                                                    <a class="btn btn-info" href="/CarDetails/Index/@item.EncodedVehicleID">
                                                        <span class="fa fa-list"></span>
                                                        See details
                                                    </a>
                                                </div>
                                                }
                                                else
                                                {
                                                <div class="increaseOffer">
                                                    <a class="btn btn-warning" href="javascript:void(0)">Make an offer</a>
                                                </div>

                                                <div class="makeCounterOffer">
                                                    <a class="btn btn-info" href="/CarDetails/Index/@item.EncodedVehicleID">
                                                        <span class="fa fa-list"></span>
                                                        See details
                                                    </a>
                                                </div>
                                    }
                                            </td>
                                        </tr>
                                        count = count + 1;
                                }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="adbanner">
                    <span>Ad Banner</span>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>


<script>
    $(document).ready(function () {
        $('#VehiclesShortlisted').dataTable();
    });
</script>

AutoBid/Views/Buyer/_BuyerLink.cshtml
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<div class="row auction_house">
    <ul class="nav nav-pills nav-justified">
        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "VehiclesIBought" ? "active" : "")"><a href='@Url.Action("VehiclesIBought", "Buyer")'>Vehicles I have bought</a></li>
        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "VehiclesIAmSelling" ? "active" : "")"><a href='@Url.Action("VehiclesIAmSelling", "Buyer")'>Vehicles I'm Selling</a></li>
        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "VehiclesShortlisted" ? "active" : "")"><a href='@Url.Action("VehiclesShortlisted", "Buyer")'>Shortlisted Vehicles</a></li>
        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "VehiclesOffersMade" ? "active" : "")"><a href='@Url.Action("VehiclesOffersMade", "Buyer")'>Offers made</a></li>
        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "BuyerAccount" ? "active" : "")"><a href='@Url.Action("BuyerAccount", "Buyer")'>Accounts</a></li>
    </ul>
</div>